[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/search/suggestions"
  to = "/.netlify/functions/suggestions"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/courses/:bvId"
  to = "/.netlify/functions/courses?bvId=:bvId"
  status = 200

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/categories"
  status = 200

[[redirects]]
  from = "/api/fetch-course"
  to = "/.netlify/functions/fetch-course"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
